# Generated by Django 5.0.8 on 2024-10-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Haiku',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_taken', models.DateField()),
                ('photo', models.ImageField(upload_to='photos/')),
                ('collaborated', models.BooleanField(default=False)),
            ],
        ),
    ]
