# Generated by Django 5.0.1 on 2024-10-16 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_haiku_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
