# Generated by Django 5.0.8 on 2024-10-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_photo_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='discard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='folder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='gallery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='insta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='wbord',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='x',
            field=models.BooleanField(default=False),
        ),
    ]
