# Generated by Django 5.0.1 on 2024-10-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_photo_discard_photo_done_photo_folder_photo_gallery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='haiku',
            name='instagram_tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
